// LIFELINE AI — Incident brief view
import { getState, store } from "../store.js";
import { createLocationLink, formatTimeAgo } from "../ui.js";
import { INCIDENT_STATUS_LABELS, INCIDENT_TYPES } from "../types.js";

export function initIncidentBrief(params = {}) {
  const state = getState();
  const incident = params.incident || state.ui.selectedIncident || state.incidents[0];
  if (!incident) return '<div class="card"><p>No incident found.</p></div>';

  const typeInfo = INCIDENT_TYPES.find(t => t.id === incident.type) || { label: incident.type || "Unknown", icon: "📋", color: "type-other" };
  const statusInfo = INCIDENT_STATUS_LABELS[incident.status] || { label: incident.status, color: "badge-gray" };
  const location = incident.location;
  const mapLink = location && location.latitude !== undefined && location.longitude !== undefined
    ? createLocationLink(location.latitude, location.longitude)
    : null;

  const observations = incident.observations || [];
  const missing = incident.missingInfo || [];

  return `
    <div class="incident-brief">
      <div class="card">
        <div class="flex-between">
          <div>
            <span class="badge ${typeInfo.color}" style="font-size:20px;">${typeInfo.icon}</span>
            <span style="font-size:20px; font-weight:700; margin-left:8px;">${esc(typeInfo.label)}</span>
          </div>
          <span class="badge ${statusInfo.color}">${statusInfo.label}</span>
        </div>

        <div class="divider"></div>

        <p class="text-small text-muted">
          Incident ID: ${esc(incident.id)} · Reported ${formatTimeAgo(incident.timestamp)}
        </p>

        <h3>Observations</h3>
        ${observations.length > 0 ? `
          <ul style="list-style:none; padding-left:0;">
            ${observations.map(o => `<li style="padding:4px 0;">✓ ${esc(o)}</li>`).join('')}
          </ul>
        ` : '<p class="mu">No specific observations recorded.</p>'}

        ${missing.length > 0 ? `
        <h3>Unknown</h3>
        <ul style="list-style:none; padding-left:0;">
          ${missing.map(m => `<li style="padding:4px 0; color:var(--text-secondary);">? ${esc(m)}</li>`).join('')}
        </ul>
        ` : ''}

        ${incident.urgency ? `
        <div class="mt-3">
          <span class="badge ${getUrgencyBadge(incident.urgency)}">${esc(incident.urgency.toUpperCase())}</span>
        </div>` : ''}
      </div>

      <div class="card">
        <h3>Location</h3>
        ${location && location.latitude !== undefined ? `
          <div style="font-size:13px; color:var(--text-secondary); line-height:1.8;">
            <div><b>Latitude:</b> ${location.latitude.toFixed(6)}</div>
            <div><b>Longitude:</b> ${location.longitude.toFixed(6)}</div>
            <div><b>Accuracy:</b> ${location.accuracy ? `±${Math.round(location.accuracy)}m` : "Unknown"}</div>
            <div><b>Captured:</b> ${formatTimeAgo(location.timestamp)}</div>
            <div><b>Type:</b> ${esc(location.sourceLabel || location.source)}</div>
          </div>
          ${mapLink ? `<a href="${mapLink}" target="_blank" rel="noopener" class="btn btn-secondary btn-sm" style="margin-top:12px;">OPEN MAP</a>` : ''}
        ` : location && location.description ? `
          <p>${esc(location.description)}</p>
          <span class="tag tag-gray">Text-described location</span>
        ` : `
          <p class="mu">No location captured.</p>
          <button type="button" class="btn btn-secondary btn-sm" data-action="navigate" data-to="location">
            CAPTURE LOCATION
          </button>
         `}
      </div>

      <div class="card">
        <h3>AI Classification</h3>
        <p class="mu">${esc(incident.aiClassification || "Classified with local rules engine.")}</p>
        <p class="text-small text-muted">
          ${incident.provider === "groq" ? "Generated by Groq Cloud AI" : "Generated by local rules engine"}
          ${incident.confidence !== undefined ? ` · Confidence: ${Math.round(incident.confidence * 100)}%` : ""}
        </p>
      </div>

      <div class="card">
        <div class="btn-row">
          <button class="btn btn-primary" data-action="navigate" data-to="escalation" data-params='{"incidentId":"${incident.id}}">
            SMART ESCALATION
          </button>
          <button type="button" class="btn btn-secondary" data-action="copy-brief" data-id="${incident.id}">COPY BRIEF</button>
        </div>
      </div>

      <div class="card">
        <h3>Verification</h3>
        <p class="mu">This incident has not been independently verified.</p>
        <div class="btn-row">
          <button class="btn btn-secondary btn-sm" data-action="verify-incident" data-id="${incident.id}">Mark as Verified</button>
          <button class="btn btn-secondary btn-sm" data-action="resolve-incident" data-id="${incident.id}">Mark as Resolved</button>
          <button class="btn btn-secondary btn-sm" data-action="false-alarm" data-id="${incident.id}">Mark as False Alarm</button>
        </div>
      </div>
    </div>
  `;
}

function getUrgencyBadge(urgency) {
  const map = {
    information: "badge-ready",
    monitor: "badge-monitor",
    verify: "badge-verify",
    urgent: "badge-urgent",
    immediate: "badge-immediate",
  };
  return map[urgency] || "badge-gray";
}
